// script.js
const languageData = {
    fr: {
        home: 'Accueil',
        addNote: 'Ajouter une Note',
        notesList: 'Liste des Notes',
        diploma: 'Générer un Diplôme',
        stats: 'Statistiques & Suivi',
        clearNotes: 'Supprimer toutes les notes',
        exportNotes: 'Exporter les Notes',
        studentNameLabel: 'Nom de l\'étudiant',
        subjectLabel: 'Matière',
        gradeLabel: 'Note (0-20)',
        submitButton: 'Ajouter',
        diplomaTitle: 'Générer un Diplôme',
        statsTitle: 'Statistiques & Suivi',
        moyenneLabel: 'Moyenne des notes :',
        addNoteTitle: 'Ajouter une Note',
        notesListTitle: 'Liste des Notes',
        generateDiplomaButton: 'Générer le Diplôme',
        exportPdfButton: 'Exporter en PDF',
    },
    en: {
        home: 'Home',
        addNote: 'Add a Note',
        notesList: 'Notes List',
        diploma: 'Generate Diploma',
        stats: 'Statistics & Tracking',
        clearNotes: 'Clear All Notes',
        exportNotes: 'Export Notes',
        studentNameLabel: 'Student Name',
        subjectLabel: 'Subject',
        gradeLabel: 'Grade (0-20)',
        submitButton: 'Add',
        diplomaTitle: 'Generate Diploma',
        statsTitle: 'Statistics & Tracking',
        moyenneLabel: 'Average Grade:',
        addNoteTitle: 'Add a Note',
        notesListTitle: 'Notes List',
        generateDiplomaButton: 'Generate Diploma',
        exportPdfButton: 'Export to PDF',
    },
    ar: {
        home: 'الصفحة الرئيسية',
        addNote: 'إضافة درجة',
        notesList: 'قائمة الدرجات',
        diploma: 'إنشاء شهادة',
        stats:
